name: Spinner package path test 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install "."
        mkdir other-folder
    - name: Sleep and plot
      run: |
         cd other-folder
         spinner run ../docs/examples/sleep_plot.yaml
         spinner export
    - name: upload produced graphs
      uses: actions/upload-artifact@v4
      with:
        name: generated graphs
        path: |
          other-folder/benchdata.html
          other-folder/benchdata.ipynb
          other-folder/output-benchdata/